# Generated by Django 3.0 on 2020-06-29 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='question',
            old_name='data',
            new_name='date',
        ),
    ]
